name: Build Lindroid Chroot

on:
  workflow_dispatch:

jobs:
  build:
    name: Debos Chroot Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Debos & Dependencies
        run: |
          sudo apt update
          sudo apt install -y debos qemu-user-static wget

      - name: Make shell scripts executable
        run: |
         chmod +x rootfs-templates/scripts/genimage.sh
         chmod +x rootfs-templates/scripts/setup-system.sh
         chmod +x rootfs-templates/scripts/setup-user.sh
         chmod +x public-key.asc

      - name: Copy Lindroid GPG key from repo
        run: |
          mkdir -p rootfs/buildd/sources
          cp public-key.asc rootfs/buildd/sources/public-key.asc

      - name: Run Debos
        run: |
          sudo debos --disable-fakemachine rootfs-templates/lindroid_plasma.yaml

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: lindroid-chroot
          path: out/lindroid-chroot.tar.gz
          retention-days: 14
