name: Build Lindroid Chroot

on:
  workflow_dispatch:

jobs:
  build:
    name: Debos Chroot Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Debos & Dependencies
        run: |
          sudo apt update
          sudo apt install -y debos qemu-user-static wget

      - name: Make shell scripts executable
        run: |
         chmod +x rootfs-templates/scripts/genimage.sh
         chmod +x rootfs-templates/scripts/setup-system.sh
         chmod +x rootfs-templates/scripts/setup-user.sh
         chmod +x public-key.asc

      - name: Copy Lindroid GPG key from repo
        run: |
          mkdir -p rootfs/buildd/sources
          cp public-key.asc rootfs/buildd/sources/public-key.asc

      - name: Run Debos
        run: |
          sudo debos --disable-fakemachine rootfs-templates/lindroid_plasma.yaml


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lindroid-out-${{ matrix.config.arch }}-${{ matrix.config.edition }}
          path: out/*
          if-no-files-found: error
          retention-days: 1

  prepare:
    runs-on: ubuntu-22.04
    name: Create GitHub release
    needs: build
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}${{ steps.create_nightly.outputs.upload_url }}

    steps:
      - name: Free up some storage
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Delete old nightly release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        if: startsWith(github.ref, 'refs/tags/lindroid') != true
        with:
          delete_release: true # default: false
          tag_name: nightly # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Tag snapshot
        if: startsWith(github.ref, 'refs/tags/lindroid') != true
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: nightly

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: lindroid-out

      - name: Create SHA256SUMS
        run: |
          cd lindroid-out
          for x in lindroid-out-*; do
            cd $x
            sha256sum * >> ../SHA256SUMS
            cd ..
          done

      - name: Create stable release (drafted)
        id: create_release
        if: startsWith(github.ref, 'refs/tags/lindroid')
        uses: softprops/action-gh-release@v1
        with:
          files: lindroid-out/SHA256SUMS
          tag_name: ${{ github.ref }}
          draft: true
          prerelease: false
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create nightly release
        id: create_nightly
        if: startsWith(github.ref, 'refs/tags/lindroid') != true
        uses: softprops/action-gh-release@v1
        with:
          files: lindroid-out/SHA256SUMS
          tag_name: nightly
          draft: false
          prerelease: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  publish:
    runs-on: ubuntu-22.04
    needs: [once, prepare]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}${{ steps.create_nightly.outputs.upload_url }}

    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.once.outputs.matrix) }}

    name: Publish ${{ matrix.config.job_name }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: lindroid-out-${{ matrix.config.arch }}-${{ matrix.config.edition }}
          path: lindroid-out

      - name: Create stable release (drafted)
        id: create_release
        if: startsWith(github.ref, 'refs/tags/lindroid')
        uses: softprops/action-gh-release@v1
        with:
          files: lindroid-out/*
          tag_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Create nightly release
        id: create_nightly
        if: startsWith(github.ref, 'refs/tags/lindroid') != true
        uses: softprops/action-gh-release@v1
        with:
          files: lindroid-out/*
          tag_name: nightly
          draft: false
          prerelease: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
