name: debian-trixie-rootfs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build Debian Trixie RootFS

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y debootstrap wget gnupg

      - name: Bootstrap Debian Trixie (symlink to bookworm)
        run: |
          export SUITE=trixie
          export TARGET=$PWD/rootfs
          export MIRROR=http://deb.debian.org/debian
          export VARIANT=minbase

          sudo ln -sf /usr/share/debootstrap/scripts/bookworm /usr/share/debootstrap/scripts/trixie
          sudo debootstrap --variant=$VARIANT --arch=amd64 $SUITE $TARGET $MIRROR

      - name: Copy Lindroid GPG key
        run: |
          mkdir -p rootfs/buildd/sources
          wget -O rootfs/buildd/sources/public-key.asc https://repo.lindroid.org/repository/lindroid/public-key.asc

      - name: Configure Lindroid repo + install packages
        run: |
          sudo chroot rootfs /bin/bash -c "
          mkdir -p /etc/apt/keyrings
          cp /buildd/sources/public-key.asc /etc/apt/keyrings/lindroid.asc
          echo 'deb [signed-by=/etc/apt/keyrings/lindroid.asc] https://repo.lindroid.org/repository/lindroid trixie main' > /etc/apt/sources.list.d/lindroid.list
          apt update || true
          DEBIAN_FRONTEND=noninteractive apt install -y \
            libhybris libhybris-test lindroid-quirks \
            nano strace sudo sddm adduser locales \
            desktop-base evtest iproute2 \
            libpipewire-module-lindroid libcanberra-pulse pipewire-audio wireplumber \
            pipewire-pulse pipewire-alsa pipewire-jack \
            kde-full kwin-wayland qtwayland5 maliit-keyboard \
            sddm-theme-debian-breeze plasma-workspace firefox-esr drihybris
          "

      - name: Archive RootFS
        run: |
          sudo tar -czf debian-trixie-rootfs.tar.gz -C rootfs .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-trixie-rootfs
          path: debian-trixie-rootfs.tar.gz
