name: Build Lindroid RootFS

on:
  workflow_dispatch:
  push:
    branches:
      - trixie
  schedule:
    - cron: "59 23 * * *"

jobs:
  once:
    runs-on: ubuntu-22.04
    name: Generate matrix
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate matrix
        id: gen-matrix
        run: |
          JOBS="$(./generate_recipe.py --matrix)"
          echo ::set-output name=matrix::${JOBS}

  build:
    runs-on: ubuntu-22.04
    needs: once

    strategy:
      fail-fast: true
      matrix:
        config: ${{ fromJson(needs.once.outputs.matrix) }}

    name: ${{ matrix.config.job_name }}

    steps:
      - name: Get current date
        run: echo "current_date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set suffix
        run: echo "release_suffix=_${{ env.current_date }}" >> $GITHUB_ENV

      - name: Set nightly version
        if: startsWith(github.ref, 'refs/tags/lindroid') != true
        run: echo "LINDROID_VERSION=nightly" >> $GITHUB_ENV

      - name: Set version
        if: startsWith(github.ref, 'refs/tags/lindroid') == true
        run: echo "LINDROID_VERSION=$(echo ${{ github.ref }} | rev | cut -d'/' -f1 | rev)" >> $GITHUB_ENV

      - name: Set identifier
        run: echo "LINDROID_IDENTIFIER=${{ matrix.config.arch }}-${{ matrix.config.edition }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: 'true'
          submodules: 'recursive'

      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Create build output dir
        run: mkdir -p /tmp/buildd-results

      - name: Create hook file for CGroup v1
        run: |
          mkdir -p hooks
          echo "- action: run" > hooks/cgroup-v1.yaml
          echo "  description: Force cgroupv1 compatibility" >> hooks/cgroup-v1.yaml
          echo "  chroot: true" >> hooks/cgroup-v1.yaml
          echo "  command: |" >> hooks/cgroup-v1.yaml
          echo "    mkdir -p /sys/fs/cgroup/{cpu,cpuacct,cpuset,devices,memory,pids}" >> hooks/cgroup-v1.yaml
          echo "    mount -t cgroup -o cpu cpu /sys/fs/cgroup/cpu" >> hooks/cgroup-v1.yaml
          echo "    mount -t cgroup -o cpuacct cpuacct /sys/fs/cgroup/cpuacct" >> hooks/cgroup-v1.yaml
          echo "    mount -t cgroup -o cpuset cpuset /sys/fs/cgroup/cpuset" >> hooks/cgroup-v1.yaml
          echo "    mount -t cgroup -o devices devices /sys/fs/cgroup/devices" >> hooks/cgroup-v1.yaml
          echo "    mount -t cgroup -o memory memory /sys/fs/cgroup/memory" >> hooks/cgroup-v1.yaml
          echo "    mount -t cgroup -o pids pids /sys/fs/cgroup/pids" >> hooks/cgroup-v1.yaml

      - name: Pull builder container
        run: docker pull registry.lindroid.org/lindroid/rootfs-builder:next-amd64

      - name: Start Container
        run: |
          echo "CONTAINER_HASH=$(docker run --detach --privileged \
            -v /tmp/buildd-results:/buildd/out \
            -v /dev:/host-dev \
            -v /sys/fs/cgroup:/sys/fs/cgroup \
            -v ${PWD}:/buildd/sources \
            --security-opt seccomp:unconfined \
            registry.lindroid.org/lindroid/rootfs-builder:next-amd64 \
            tail -f /dev/null)" >> $GITHUB_ENV


      - name: Build rootfs with injected CGroup v1 hook
        run: |
          docker exec $CONTAINER_HASH /bin/sh -c "\
            cd /buildd/sources && \
            ./generate_recipe.py && \
            sed -i '/^actions:/r hooks/cgroup-v1.yaml' /
            debos --disable-fakemachine generated/lindroid-${{ matrix.config.edition }}-${{ matrix.config.arch }}.yaml"
      
      - name: Stop and remove container
        if: always()
        run: docker rm -f $CONTAINER_HASH || true
