name: Build Lindroid Base RootFS

on:
  workflow_dispatch:

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    env:
      SUITE: trixie
      ARCH: arm64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup QEMU for ARM64
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Pull compatible container
        run: docker pull ubuntu:20.04

      - name: Start Container with cgroup support
        run: |
          echo CONTAINER_HASH=$(docker run --detach --privileged -v /tmp/buildd-results:/buildd/out -v /dev:/host-dev -v /sys/fs/cgroup:/sys/fs/cgroup -v ${PWD}:/buildd/sources --security-opt seccomp:unconfined ubuntu:20.04 /sbin/init) >> $GITHUB_ENV

      - name: Install dependencies and qemu-aarch64-static in container
        run: |
          docker exec $CONTAINER_HASH bash -c "\
            apt update && apt install -y qemu-user-static systemd debootstrap && \
            [ -f /usr/bin/qemu-aarch64-static ] || cp $(which qemu-aarch64-static) /usr/bin/"

      - name: Verify container status
        run: |
          docker exec $CONTAINER_HASH bash -c "ps aux"  # Verifikasi apakah systemd berjalan dengan baik

      - name: Run Debos in container
        run: |
          docker exec $CONTAINER_HASH bash -c "\
            cd /buildd/sources && \
            debos --disable-fakemachine rootfs-templates/lindroid_base.yaml"

      - name: Stop container
        if: always()
        run: |
          docker stop $CONTAINER_HASH || true
