name: Build Lindroid Base RootFS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SUITE: trixie
      ARCH: arm64

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2
      with:
          lfs: 'true'
          submodules: 'recursive'

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: QEMU set-up
      uses: docker/setup-qemu-action@v1

    - name: Create build dir
      run: mkdir -p /tmp/buildd-results

    - name: Pull container
      run: docker pull registry.lindroid.org/lindroid/rootfs-builder:next-amd64

    - name: Start Container
      run: echo CONTAINER_HASH=$(docker run --detach --privileged -v /tmp/buildd-results:/buildd/out -v /dev:/host-dev -v /sys/fs/cgroup:/sys/fs/cgroup -v ${PWD}:/buildd/sources --security-opt seccomp:unconfined registry.lindroid.org/lindroid/rootfs-builder:next-amd64 /sbin/init) >> $GITHUB_ENV
    
    - name: Build rootfs
      run: |
         docker exec $CONTAINER_HASH /bin/sh -c "\
         cd /buildd/sources && \
         debos --disable-fakemachine rootfs-templates/lindroid_base.yaml'

    # Copy the result to the host
    - name: Copy result to host
      run: docker cp $CONTAINER_HASH:/buildd/out /tmp/buildd-results
